name = "GeologicTime"
uuid = "7ffcb9c5-a22b-481a-ba2a-c280bedef8cf"
authors = ["Yu-Chang YANG <yang.yc.allium@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Aqua = "0.6"
DelimitedFiles = "1"
Requires = "1.3.0"
Test = "1"
julia = "1.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
